apiVersion: extensions/v1beta1  # for kubernetes 1.5
# apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
#            image: nginx:1.7.9
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-vol
      volumes:
      - name: nginx-vol
        hostPath:
          path: "/var/data"
#        emptyDir: {}
      # emptyDir 不显式声明宿主机目录的 Volume。所以，Kubernetes 也会在宿主机上创建一个临时目录，这个目录将来就会被绑定挂载到容器所声明的 Volume 目录上
      # hostPath 模式与之相反

